
import { PageHeader } from '@/components/page-header';
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card';

export default function StormWaterPage() {
  return (
    <div className="space-y-8">
      <PageHeader
        title="Storm Water Design Concepts"
        description="Understanding common methods for estimating storm water runoff and flow."
      />

      <Card>
        <CardHeader>
          <CardTitle>The Rational Method</CardTitle>
          <CardDescription>
            The core of the method is the formula: Q = C * i * A
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-6">
          <div className="prose prose-sm dark:prose-invert max-w-none">
            <p>
                The Rational Method is used to predict the peak rate of runoff from a small drainage area for a given rainfall event. It's based on the assumption that the peak runoff occurs when the entire drainage area is contributing to the flow.
            </p>
            <h4>Components of the Formula</h4>
            <ul>
              <li>
                <strong>Q = Peak Runoff Rate:</strong> The maximum flow rate generated by the rainfall event, typically expressed in cubic feet per second (cfs) or cubic meters per second (cms). This value is critical for designing drainage structures like pipes, culverts, and ditches.
              </li>
              <li>
                <strong>C = Runoff Coefficient:</strong> This is a dimensionless value that represents the fraction of rainfall that becomes surface runoff. It depends on the characteristics of the surface, such as its permeability. A paved parking lot will have a very high 'C' value (e.g., 0.95) because most of the rain runs off, while a flat, sandy lawn will have a very low 'C' value (e.g., 0.10) because most of the rain soaks in.
              </li>
              <li>
                <strong>i = Rainfall Intensity:</strong> The average rate of rainfall over a specific duration, typically expressed in inches per hour (in/hr) or millimeters per hour (mm/hr). The intensity is chosen based on the "design storm" for the area (e.g., a 10-year storm, 25-year storm).
              </li>
              <li>
                <strong>A = Drainage Area:</strong> The size of the area that collects rainfall and contributes to the runoff, measured in acres or hectares.
              </li>
            </ul>
          </div>
        </CardContent>
      </Card>
      
      <Card>
        <CardHeader>
          <CardTitle>NRCS Curve Number Method</CardTitle>
          <CardDescription>
            Estimates runoff depth based on rainfall, soil type, and land cover.
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-6">
          <div className="prose prose-sm dark:prose-invert max-w-none">
            <p>
                The Natural Resources Conservation Service (NRCS) Curve Number method is a widely used empirical model that estimates direct runoff from a rainfall event. It is more sophisticated than the Rational Method as it accounts for initial water losses.
            </p>
            <h4>Key Concepts and Formula</h4>
             <ul>
              <li>
                <strong>Curve Number (CN):</strong> An empirical value (30-100) that represents the runoff potential of an area. It is based on soil type, land use/cover, and hydrologic condition. A higher CN means higher runoff potential (e.g., pavement is ~98), while a lower CN means lower runoff potential (e.g., healthy woods are ~30).
              </li>
               <li>
                <strong>Potential Maximum Retention (S):</strong> The theoretical maximum amount of water the soil can absorb after runoff begins. It is directly related to the CN: <br/><code>S = (1000 / CN) - 10</code> (for inches).
              </li>
               <li>
                <strong>Initial Abstraction (Iₐ):</strong> The amount of water lost before runoff starts, including interception by plants and surface storage. It is typically estimated as 20% of S: <code>Iₐ = 0.2 * S</code>.
              </li>
               <li>
                <strong>Runoff Depth (Q):</strong> The core formula calculates the depth of runoff over the entire area: <br/><code>Q = (P - Iₐ)² / (P - Iₐ + S)</code>, where P is the total rainfall depth. Runoff only occurs if P &gt; Iₐ.
              </li>
            </ul>
             <p>This method is valuable for analyzing the effects of land development on runoff and for designing stormwater management facilities like detention ponds.</p>
          </div>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Manning's Equation</CardTitle>
          <CardDescription>
            Calculates the flow velocity in an open channel (like a ditch, stream, or partially full pipe).
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-6">
          <div className="prose prose-sm dark:prose-invert max-w-none">
            <p>
               Once you know the peak runoff rate (Q) from the Rational or NRCS method, Manning's Equation helps you design the channel that will carry that flow.
            </p>
            <h4>Formula: V = (k/n) * Rₕ^(2/3) * S^(1/2)</h4>
            <ul>
              <li>
                <strong>V = Velocity:</strong> The average speed of the water in the channel (ft/s or m/s).
              </li>
              <li>
                <strong>k:</strong> A unit conversion factor (1.49 for Imperial units, 1.0 for Metric).
              </li>
              <li>
                <strong>n = Manning's Roughness Coefficient:</strong> Represents the friction of the channel surface. A smooth concrete channel has a low 'n' (e.g., 0.013), while a natural stream with heavy vegetation has a high 'n' (e.g., 0.075).
              </li>
               <li>
                <strong>Rₕ = Hydraulic Radius:</strong> The efficiency of the channel's shape, calculated as the cross-sectional area of the flow (A) divided by the wetted perimeter (P). A deep, narrow channel is more efficient than a wide, shallow one.
              </li>
              <li>
                <strong>S = Channel Slope:</strong> The longitudinal slope of the channel bed.
              </li>
            </ul>
          </div>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Orifice Equation</CardTitle>
          <CardDescription>
            Calculates the flow rate through a submerged opening (orifice) in a tank or reservoir wall.
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-6">
          <div className="prose prose-sm dark:prose-invert max-w-none">
            <p>
               The Orifice Equation is a fundamental principle in fluid dynamics used to determine the discharge from a tank or detention pond through a small opening. It is based on Bernoulli's principle and is essential for designing outlet structures in storm water management systems.
            </p>
            <h4>Formula: Q = C * A * √(2gh)</h4>
            <ul>
              <li>
                <strong>Q = Flow Rate:</strong> The volume of water passing through the orifice per unit of time (cfs or cms).
              </li>
              <li>
                <strong>C = Discharge Coefficient:</strong> A dimensionless factor that accounts for energy losses as water contracts and passes through the orifice. For a sharp-edged orifice, a value of <strong>0.61</strong> is commonly used.
              </li>
               <li>
                <strong>A = Area of the Orifice:</strong> The cross-sectional area of the opening (ft² or m²).
              </li>
              <li>
                <strong>g = Acceleration due to Gravity:</strong> A constant, which is 32.2 ft/s² in imperial units or 9.81 m/s² in metric units.
              </li>
               <li>
                <strong>h = Head:</strong> The vertical distance from the centerline of the orifice to the water surface (ft or m). This pressure is what drives the flow.
              </li>
            </ul>
          </div>
        </CardContent>
      </Card>

    </div>
  );
}
